import { existsSync, readFileSync } from 'node:fs'
import { Project } from 'ts-morph'
import { ok, err, ERROR_CODES } from '../errors.js'
import type { Result, SkeletalError } from '../errors.js'
import type { SkeletalCandidate } from '../ast-scanner/types.js'
import type { SkeletonTree } from '../classifier/types.js'
import type { PrimitivesConfig } from '../config/types.js'
import type { Logger } from '../logger.js'
import { printSkeletonTree } from './printer.js'
import type { GeneratedFile } from './types.js'

function computeUnifiedDiff(oldContent: string, newContent: string): string | null {
  if (oldContent === newContent) return null
  const oldLines = oldContent.split('\n')
  const newLines = newContent.split('\n')
  const lines: string[] = ['--- existing', '+++ generated']
  const maxLen = Math.max(oldLines.length, newLines.length)
  for (let i = 0; i < maxLen; i++) {
    const oldLine = oldLines[i]
    const newLine = newLines[i]
    if (oldLine === undefined && newLine !== undefined) {
      lines.push(`+${newLine}`)
    } else if (oldLine !== undefined && newLine === undefined) {
      lines.push(`-${oldLine}`)
    } else if (oldLine !== newLine) {
      if (oldLine !== undefined) lines.push(`-${oldLine}`)
      if (newLine !== undefined) lines.push(`+${newLine}`)
    }
  }
  return lines.join('\n')
}

function validateTypeScript(content: string, componentName: string): boolean {
  try {
    const project = new Project({
      useInMemoryFileSystem: true,
      compilerOptions: {
        jsx: 4, /* ReactJSX */
        skipLibCheck: true,
      },
    })
    project.createSourceFile(`${componentName}.skeleton.tsx`, content)
    // If we get here without exception, the source is parseable
    return true
  } catch {
    return false
  }
}

function buildSkeletonContent(
  candidate: SkeletalCandidate,
  tree: SkeletonTree,
  primitivesConfig?: PrimitivesConfig,
): string {
  const { name, astHash, pattern } = candidate
  const skeletonName = `${name}Skeleton`
  const body = printSkeletonTree(tree, 2, primitivesConfig)

  return [
    `// skeletal:hash:${astHash}`,
    `// skeletal:pattern:${pattern}`,
    '// This file was generated by skeletal-ui. Do not edit manually.',
    `// To customize, run: skeletal-ui eject ${name}`,
    '\'use client\'',
    '',
    'import { Sk } from \'skeletal-ui\'',
    '',
    `export function ${skeletonName}() {`,
    '  return (',
    '    <div>',
    body,
    '    </div>',
    '  )',
    '}',
    '',
    `export { ${skeletonName} as skeleton }`,
    '',
  ].join('\n')
}

function buildSkeletonContentFromBody(
  candidate: SkeletalCandidate,
  body: string,
): string {
  const { name, astHash, pattern } = candidate
  const skeletonName = `${name}Skeleton`

  return [
    `// skeletal:hash:${astHash}`,
    `// skeletal:pattern:${pattern}`,
    '// This file was generated by skeletal-ui. Do not edit manually.',
    `// To customize, run: skeletal-ui eject ${name}`,
    '\'use client\'',
    '',
    'import { Sk } from \'skeletal-ui\'',
    '',
    `export function ${skeletonName}() {`,
    '  return (',
    body,
    '  )',
    '}',
    '',
    `export { ${skeletonName} as skeleton }`,
    '',
  ].join('\n')
}

export function generateSkeletonFromBody(
  candidate: SkeletalCandidate,
  body: string,
  outputPath: string,
  logger: Logger,
): Result<GeneratedFile, SkeletalError> {
  const content = buildSkeletonContentFromBody(candidate, body)
  const skeletonName = `${candidate.name}Skeleton`

  if (!validateTypeScript(content, candidate.name)) {
    logger.error(`Codegen produced invalid TypeScript for ${candidate.name}`)
    return err({
      code: ERROR_CODES.CODEGEN_INVALID_OUTPUT,
      message: `Generated skeleton for '${candidate.name}' is not valid TypeScript. This is a skeletal bug. Please report at github.com/...`,
      recoverable: false,
    })
  }

  const isNew = !existsSync(outputPath)
  let diff: string | null = null

  if (!isNew) {
    try {
      const existing = readFileSync(outputPath, 'utf-8')
      diff = computeUnifiedDiff(existing, content)
    } catch {
      // treat as new
    }
  }

  return ok({
    componentName: candidate.name,
    skeletonName,
    outputPath,
    content,
    hash: candidate.astHash,
    pattern: candidate.pattern,
    isNew,
    diff,
  })
}

export function generateSkeleton(
  candidate: SkeletalCandidate,
  tree: SkeletonTree,
  outputPath: string,
  logger: Logger,
  primitivesConfig?: PrimitivesConfig,
): Result<GeneratedFile, SkeletalError> {
  const content = buildSkeletonContent(candidate, tree, primitivesConfig)
  const skeletonName = `${candidate.name}Skeleton`

  // Validate generated TypeScript is parseable
  if (!validateTypeScript(content, candidate.name)) {
    logger.error(`Codegen produced invalid TypeScript for ${candidate.name}`)
    return err({
      code: ERROR_CODES.CODEGEN_INVALID_OUTPUT,
      message: `Generated skeleton for '${candidate.name}' is not valid TypeScript. This is a skeletal bug. Please report at github.com/...`,
      recoverable: false,
    })
  }

  const isNew = !existsSync(outputPath)
  let diff: string | null = null

  if (!isNew) {
    try {
      const existing = readFileSync(outputPath, 'utf-8')
      diff = computeUnifiedDiff(existing, content)
    } catch {
      // If we can't read, treat as new
    }
  }

  return ok({
    componentName: candidate.name,
    skeletonName,
    outputPath,
    content,
    hash: candidate.astHash,
    pattern: candidate.pattern,
    isNew,
    diff,
  })
}
