'use client'

import { useEffect, useRef, useState } from 'react'
import { SkeletonWrapper, Sk, lazyWithSkeleton } from 'skeletal-ui'
import { DemoCard } from '../components/DemoCard'
import { DemoCardSkeleton } from '../components/DemoCard.skeleton'
import { DemoSSR } from '../components/DemoSSR'
import { DemoSSRSkeleton } from '../components/DemoSSR.skeleton'
import { DemoDynamicSkeleton } from '../components/DemoDynamic.skeleton'
import 'skeletal-ui/styles.css'

const DemoDynamic = lazyWithSkeleton(() => import('../components/DemoDynamic'))

export default function DemoPage() {
  const [loading, setLoading] = useState(false)
  const [animated, setAnimated] = useState(true)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const toggleLoading = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    if (loading) {
      setLoading(false)
    } else {
      setLoading(true)
      timerRef.current = setTimeout(() => setLoading(false), 4000)
    }
  }

  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current) }, [])

  return (
    <div className="min-h-screen bg-white dark:bg-neutral-950 text-gray-900 dark:text-gray-100">

      {/* Header */}
      <header className="border-b border-gray-200 dark:border-neutral-800 bg-white/90 dark:bg-neutral-950/90 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="font-bold text-gray-900 dark:text-white">skeletal-ui</span>
            <span className="text-gray-300 dark:text-gray-700">/</span>
            <span className="text-gray-500 dark:text-gray-400 text-sm">demo</span>
          </div>
          <a
            href="/overview"
            className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            ← Docs
          </a>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-12 flex flex-col gap-20">

        {/* ── Patterns demo ───────────────────────────────────────────── */}
        <section>
          <div className="flex flex-col sm:flex-row sm:items-end gap-4 mb-8">
            <div className="flex-1">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">
                Four patterns, one API
              </h2>
              <p className="text-gray-500 dark:text-gray-400 text-sm">
                All skeletons auto-generated by{' '}
                <code className="text-indigo-600 dark:text-indigo-400 font-mono">skeletal-ui analyze</code>.
                Toggle loading and animation to inspect the output.
              </p>
            </div>

            {/* Controls */}
            <div className="flex items-center gap-2 flex-shrink-0">
              <button
                onClick={toggleLoading}
                className={`flex items-center gap-2 text-xs font-semibold px-4 py-2 rounded-lg border transition-all ${
                  loading
                    ? 'bg-indigo-50 dark:bg-indigo-500/15 border-indigo-200 dark:border-indigo-500/30 text-indigo-700 dark:text-indigo-300'
                    : 'bg-white dark:bg-neutral-800 border-gray-200 dark:border-neutral-700 text-gray-600 dark:text-gray-300 hover:border-gray-400 dark:hover:border-neutral-500'
                }`}
              >
                <span className={`w-2 h-2 rounded-full ${loading ? 'bg-indigo-500 animate-pulse' : 'bg-green-500'}`} />
                {loading ? 'Loading…' : 'Simulate fetch'}
              </button>

              <button
                onClick={() => setAnimated(a => !a)}
                className={`flex items-center gap-2 text-xs font-semibold px-4 py-2 rounded-lg border transition-all ${
                  animated
                    ? 'bg-white dark:bg-neutral-800 border-gray-200 dark:border-neutral-700 text-gray-600 dark:text-gray-300 hover:border-gray-400 dark:hover:border-neutral-500'
                    : 'bg-gray-100 dark:bg-neutral-900 border-gray-300 dark:border-neutral-600 text-gray-500 dark:text-gray-400'
                }`}
              >
                <span className={`w-2 h-2 rounded-full ${animated ? 'bg-amber-400' : 'bg-gray-300 dark:bg-gray-600'}`} />
                {animated ? 'Pulse on' : 'Pulse off'}
              </button>
            </div>
          </div>

          {/* Page-layout demo — all three components visible simultaneously */}
          <div className={animated ? '' : 'sk-paused'}>
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">

              {/* Left column — article card (RSC) */}
              <div className="lg:col-span-3 flex flex-col gap-3">
                <PatternLabel tag="rsc" file="DemoSSR.skeleton.tsx" />
                <SkeletonWrapper loading={loading} fallback={<DemoSSRSkeleton />}>
                  <DemoSSR />
                </SkeletonWrapper>
              </div>

              {/* Right column — profile card (CSR) + chart (lazy) */}
              <div className="lg:col-span-2 flex flex-col gap-4">
                <div className="flex flex-col gap-3">
                  <PatternLabel tag="csr" file="DemoCard.skeleton.tsx" />
                  <SkeletonWrapper loading={loading} fallback={<DemoCardSkeleton />}>
                    <DemoCard />
                  </SkeletonWrapper>
                </div>

                <div className="flex flex-col gap-3">
                  <PatternLabel tag="lazy" file="DemoDynamic.skeleton.tsx" />
                  <SkeletonWrapper loading={loading} fallback={<DemoDynamicSkeleton />}>
                    <DemoDynamic />
                  </SkeletonWrapper>
                </div>
              </div>

            </div>
          </div>

          {/* Pattern description table */}
          <div className="mt-6 rounded-xl border border-gray-200 dark:border-neutral-800 overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 dark:border-neutral-800 bg-gray-50 dark:bg-neutral-900">
                  <th className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Pattern</th>
                  <th className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider hidden sm:table-cell">Trigger</th>
                  <th className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider hidden md:table-cell">What skeletal-ui does</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-neutral-800">
                {[
                  { tag: 'rsc', trigger: 'async component in <SkeletonWrapper>', action: 'generates skeleton, adds fallback prop' },
                  { tag: 'csr', trigger: 'non-async component in <SkeletonWrapper>', action: 'generates skeleton, adds fallback prop' },
                  { tag: 'lazy', trigger: 'React.lazy(() => import(...))', action: 'generates skeleton, replaces with lazyWithSkeleton' },
                  { tag: 'dynamic', trigger: 'next/dynamic(() => import(...))', action: 'generates skeleton, replaces with dynamicWithSkeleton' },
                ].map(p => (
                  <tr key={p.tag} className="hover:bg-gray-50 dark:hover:bg-neutral-900/50">
                    <td className="px-4 py-3">
                      <span className="text-xs font-mono text-indigo-700 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 px-2 py-0.5 rounded">
                        {p.tag}
                      </span>
                    </td>
                    <td className="px-4 py-3 hidden sm:table-cell">
                      <code className="text-xs text-gray-600 dark:text-gray-400 font-mono">{p.trigger}</code>
                    </td>
                    <td className="px-4 py-3 hidden md:table-cell text-gray-500 dark:text-gray-400 text-xs">{p.action}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ── Primitives ──────────────────────────────────────────────── */}
        <section>
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">Sk.* Primitives</h2>
            <p className="text-gray-500 dark:text-gray-400 text-sm">
              Pure CSS, zero dependencies, server-safe.{' '}
              <code className="text-indigo-600 dark:text-indigo-400 font-mono text-xs">
                {'import { Sk } from \'skeletal-ui\''}
              </code>
            </p>
          </div>
          <PrimitivesGrid animated={animated} />
        </section>

      </main>

      <footer className="border-t border-gray-200 dark:border-neutral-800 mt-8">
        <div className="max-w-5xl mx-auto px-6 py-8 flex items-center justify-between text-sm text-gray-400 dark:text-gray-600">
          <span>skeletal-ui — MIT</span>
          <a
            href="https://github.com/web-scavenger/skeletal"
            className="hover:text-gray-700 dark:hover:text-gray-400 transition-colors"
            target="_blank"
            rel="noreferrer"
          >
            GitHub →
          </a>
        </div>
      </footer>
    </div>
  )
}

/* ─── Pattern label ──────────────────────────────────────────────────────── */

function PatternLabel({ tag, file }: { tag: string; file: string }) {
  return (
    <div className="flex items-center gap-2">
      <span className="text-xs font-mono text-indigo-700 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 px-2 py-0.5 rounded">
        {tag}
      </span>
      <span className="text-xs font-mono text-gray-400 dark:text-gray-600">{file}</span>
    </div>
  )
}

/* ─── Primitives grid ────────────────────────────────────────────────────── */

function PrimitivesGrid({ animated }: { animated: boolean }) {
  const cards: { name: string; preview: React.ReactNode }[] = [
    {
      name: 'Sk.Text',
      preview: (
        <div style={{ width: '100%' }}>
          <Sk.Text lines={3} height="13px" gap="8px" lastLineWidth="50%" />
        </div>
      ),
    },
    {
      name: 'Sk.Heading',
      preview: (
        <div style={{ width: '100%' }}>
          <Sk.Heading height="24px" width="70%" />
        </div>
      ),
    },
    {
      name: 'Sk.Avatar',
      preview: (
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <Sk.Avatar size={48} />
          <Sk.Avatar size={40} shape="square" />
          <Sk.Avatar size={32} />
        </div>
      ),
    },
    {
      name: 'Sk.Image',
      preview: (
        <div style={{ width: '100%' }}>
          <Sk.Image aspectRatio="16/9" />
        </div>
      ),
    },
    {
      name: 'Sk.Button',
      preview: (
        <div style={{ display: 'flex', gap: 10 }}>
          <Sk.Button width={100} height={36} />
          <Sk.Button width={80} height={36} />
        </div>
      ),
    },
    {
      name: 'Sk.Badge',
      preview: (
        <div style={{ display: 'flex', gap: 8 }}>
          <Sk.Badge width={60} />
          <Sk.Badge width={80} />
          <Sk.Badge width={50} />
        </div>
      ),
    },
    {
      name: 'Sk.Number',
      preview: (
        <div style={{ display: 'flex', gap: 24 }}>
          <Sk.Number width={40} height="18px" outerHeight="26px" />
          <Sk.Number width={32} height="18px" outerHeight="26px" />
          <Sk.Number width={36} height="18px" outerHeight="26px" />
        </div>
      ),
    },
    {
      name: 'Sk.Icon',
      preview: (
        <div style={{ display: 'flex', gap: 12 }}>
          <Sk.Icon size={16} />
          <Sk.Icon size={20} />
          <Sk.Icon size={24} />
          <Sk.Icon size={28} />
        </div>
      ),
    },
    {
      name: 'Sk.List',
      preview: (
        <div style={{ width: '100%' }}>
          <Sk.List count={3} gap={12} renderItem={() => (
            <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <Sk.Avatar size={32} />
              <div style={{ flex: 1 }}>
                <Sk.Text width="60%" height="13px" />
              </div>
            </div>
          )} />
        </div>
      ),
    },
    {
      name: 'Sk.Card',
      preview: (
        <div style={{ width: '100%' }}>
          <Sk.Card padding={14}>
            <Sk.Heading width="55%" height="20px" />
            <Sk.Text lines={2} height="13px" gap="8px" />
            <div style={{ display: 'flex', gap: 8, marginTop: 4 }}>
              <Sk.Button width={80} height={32} />
              <Sk.Button width={64} height={32} />
            </div>
          </Sk.Card>
        </div>
      ),
    },
  ]

  return (
    <div className={`grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 ${animated ? '' : 'sk-paused'}`}>
      {cards.map(card => (
        <div
          key={card.name}
          className="rounded-xl border border-gray-200 dark:border-neutral-800 bg-gray-50 dark:bg-neutral-900 p-5 flex flex-col gap-3"
        >
          <code className="text-xs font-mono text-indigo-600 dark:text-indigo-400">{card.name}</code>
          <div className="flex-1 flex items-center">
            {card.preview}
          </div>
        </div>
      ))}
    </div>
  )
}
