// skeletal:hash:8fbc8245
// skeletal:pattern:csr
// This file was generated by skeletal-ui. Do not edit manually.
// To customize, run: skeletal-ui eject DemoFeed
'use client'

import { Sk } from 'skeletal-ui'

export function DemoFeedSkeleton() {
  return (
    <div className="w-full rounded-xl border border-slate-700 bg-slate-950 divide-y divide-slate-800">
      <div className="flex items-start gap-3 p-4">
        <Sk.Avatar size={32} />
        <div className="flex-1 min-w-0">
          <Sk.Text lines={2} height="14px" gap="14px" />
          <Sk.Text className="mt-1" lines={2} height="12px" gap="12px" />
        </div>
      </div>
      <div className="flex items-start gap-3 p-4">
        <Sk.Avatar size={32} />
        <div className="flex-1 min-w-0">
          <Sk.Text lines={2} height="14px" gap="14px" />
          <Sk.Text className="mt-1" lines={2} height="12px" gap="12px" />
        </div>
      </div>
      <div className="flex items-start gap-3 p-4">
        <Sk.Avatar size={32} />
        <div className="flex-1 min-w-0">
          <Sk.Text lines={2} height="14px" gap="14px" />
          <Sk.Text className="mt-1" lines={2} height="12px" gap="12px" />
        </div>
      </div>
      <div className="flex items-start gap-3 p-4">
        <Sk.Avatar size={32} />
        <div className="flex-1 min-w-0">
          <Sk.Text lines={2} height="14px" gap="14px" />
          <Sk.Text className="mt-1" lines={2} height="12px" gap="12px" />
        </div>
      </div>
    </div>
  )
}

export { DemoFeedSkeleton as skeleton }
