// skeletal:hash:5948fe22
// skeletal:pattern:csr
// This file was generated by skeletal-ui. Do not edit manually.
// To customize, run: skeletal-ui eject DemoCard
'use client'

import { Sk } from 'skeletal-ui'

export function DemoCardSkeleton() {
  return (
    <div className="w-full max-w-sm rounded-xl border border-slate-700 bg-slate-950 p-5 flex flex-col gap-4">
      <div className="flex items-center gap-3">
        <Sk.Avatar size={48} />
        <div className="flex-1 min-w-0">
          <Sk.Text height="14px" lineHeight="20px" width="100%" />
          <Sk.Text height="12px" lineHeight="16px" width="100%" />
        </div>
      </div>
      <Sk.Text lines={2} height="14px" gap="18px" width="87%" />
      <div className="flex gap-6 pt-2 border-t">
        <div className="flex flex-col items-center gap-0.5">
          <Sk.Number width={28} height="16px" outerHeight="24px" />
          <Sk.Text height="12px" lineHeight="16px" width="100%" />
        </div>
        <div className="flex flex-col items-center gap-0.5">
          <Sk.Number width={21} height="16px" outerHeight="24px" />
          <Sk.Text height="12px" lineHeight="16px" width="100%" />
        </div>
        <div className="flex flex-col items-center gap-0.5">
          <Sk.Number width={26} height="16px" outerHeight="24px" />
          <Sk.Text height="12px" lineHeight="16px" width="100%" />
        </div>
      </div>
    </div>
  )
}

export { DemoCardSkeleton as skeleton }
