// skeletal:hash:db321654
// skeletal:pattern:lazy
// This file was generated by skeletal-ui. Do not edit manually.
// To customize, run: skeletal-ui eject DemoDynamic
'use client'

import { Sk } from 'skeletal-ui'

export function DemoDynamicSkeleton() {
  return (
    <div className="w-full rounded-xl border border-slate-700 bg-slate-950 p-5 flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <Sk.Text height="14px" lineHeight="20px" width="104px" />
        <Sk.Text height="12px" lineHeight="16px" width="32px" />
      </div>
      <Sk.Card width="93%" height={80} padding={0} />
      <div className="flex justify-between">
        <Sk.Text height="12px" lineHeight="16px" width="25px" />
        <Sk.Text height="12px" lineHeight="16px" width="21px" />
        <Sk.Text height="12px" lineHeight="16px" width="26px" />
        <Sk.Text height="12px" lineHeight="16px" width="22px" />
        <Sk.Text height="12px" lineHeight="16px" width="14px" />
        <Sk.Text height="12px" lineHeight="16px" width="18px" />
        <Sk.Text height="12px" lineHeight="16px" width="22px" />
      </div>
    </div>
  )
}

export { DemoDynamicSkeleton as skeleton }
