// skeletal:hash:3fdfd999
// skeletal:pattern:csr
// This file was generated by skeletal-ui. Do not edit manually.
// To customize, run: skeletal-ui eject DemoArticle
'use client'

import { Sk } from 'skeletal-ui'

export function DemoArticleSkeleton() {
  return (
    <div className="w-full rounded-xl border border-slate-700 bg-slate-950 overflow-hidden">
      <Sk.Image aspectRatio="16/9" width="100%" />
      <div className="p-5 flex flex-col gap-3">
        <Sk.Text height="12px" lineHeight="16px" width="88%" />
        <Sk.Heading height="39px" width="88%" />
        <Sk.Text lines={4} height="12px" gap="10px" width="88%" />
        <div className="flex items-center justify-between pt-3 border-t">
          <div className="flex items-center gap-2">
            <Sk.Avatar size={24} />
            <Sk.Text height="12px" lineHeight="16px" width="66%" />
          </div>
          <Sk.Text height="12px" lineHeight="16px" width="21%" />
        </div>
      </div>
    </div>
  )
}

export { DemoArticleSkeleton as skeleton }
