// skeletal:hash:634735f2
// skeletal:pattern:lazy
// This file was generated by skeletal-ui. Do not edit manually.
// To customize, run: skeletal-ui eject HeavyChart
'use client'

import { Sk } from 'skeletal-ui'

export function HeavyChartSkeleton() {
  return (
    <div>
      <Sk.Card width="100%" height={200} />
    </div>
  )
}

export { HeavyChartSkeleton as skeleton }
