// skeletal:hash:e5077204
// skeletal:pattern:dynamic
// This file was generated by skeletal. Do not edit manually.
// To customize, run: skeletal eject MapComponent
'use client'

import { Sk } from 'skeletal'

export function MapComponentSkeleton() {
  return (
    <div>
    <Sk.Card width="100%" height={200} />
    </div>
  )
}

export { MapComponentSkeleton as skeleton }
