// skeletal:hash:277d33ee
// skeletal:pattern:csr
// This file was generated by skeletal. Do not edit manually.
// To customize, run: skeletal eject ProfileCard
'use client'

import { Sk } from 'skeletal-ui'

export function ProfileCardSkeleton() {
  return (
    <div>
      <Sk.Card width="100%" height={200} />
    </div>
  )
}

export { ProfileCardSkeleton as skeleton }
