// skeletal:hash:3e88132e
// skeletal:pattern:rsc
// This file was generated by skeletal. Do not edit manually.
// To customize, run: skeletal eject UserCard
'use client'

import { Sk } from 'skeletal'

export function UserCardSkeleton() {
  return (
    <div>
      <Sk.Card width="100%" height={200} />
    </div>
  )
}

export { UserCardSkeleton as skeleton }
